### PR TITLE
Revert "Meta tags"

### PR DESCRIPTION
**Pull request by wongalvis**

### CODE REVIEW

**Comment by mariobehling** [comment]
What is the goal of reverting the meta tags?

**Comment by wongalvis** [comment]
samarjeet should do this work

**Comment by mariobehling** [comment]
Please explain what is the issue with the metatags.

**Comment by wongalvis** [comment]
No, there's no issue with the metatags. Or yes there's one, I'm the one who do it, they're worthless.

**Comment by pwmvx1289** [comment]
I have my rights to remove my work.

**Pull request closed without merging**
