### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Mridulbirla13**
- A GCI-17 task
- Added additional 8 profile links.
- Also I deleted 1 link as it was placed to wrong Speaker previously.
- Here is my preview link : https://mridulbirla13.github.io/

### CODE REVIEW

**Review by ParthS007 — CHANGES_REQUESTED** [review]
@Mridulbirla13 Please provide a preview link 👍

**Comment by Mridulbirla13** [comment]
Sir I wanted to know what is preview link

**Comment by ParthS007** [comment]
@Mridulbirla13 Please go through this https://pages.github.com/ and let me know if you face any difficulty 👍

**Comment by Mridulbirla13** [comment]
Here is my preview link : https://mridulbirla13.github.io/

**Review by akshatnitd — APPROVED** [review]

**Review by ParthS007 — APPROVED** [review]

**Pull request merged**
