### PR TITLE
8 speakers added

### LINKED ISSUE #53: Adding Social Links
Adding social links to speakers of FOSSASIA summit 2015,

### PR DESCRIPTION
**Pull request by YashKumarVerma**
added 8 speakers

### CODE REVIEW

**Comment by anshumanv** [comment]
Please change the PR title to what this PR does.

**Review by isuruAb — APPROVED** [review]

**Comment by isuruAb** [comment]
Please change the PR title and add a descriptive one

**Review by anshumanv — CHANGES_REQUESTED** [review]
Please decide whether you are adding favicon or speakers.

**Comment by YashKumarVerma** [comment]
@anshumanv  actually i had to change title of different PR. and by mistake changed this one 😄

**Comment by YashKumarVerma** [comment]
the PR is to add the speakers @anshumanv

**Comment by anshumanv** [comment]
No issues then, please change this PRs title then.

**Review by anshumanv — APPROVED** [review]

**Pull request merged**
