### PR TITLE
Change dropdown menu to red

### PR DESCRIPTION
**Pull request by Ploypiti**
#80 | [Deploy link](https://ploypiti.github.io/2015.fossasia.org/)

### CODE REVIEW

**Comment by abishekvashok** [comment]
Please properly intend the code

**Comment by nzec** [comment]
@Ploypiti 
The attend column is a bit too long. I would recommend you to have `height: auto;` and then set a padding. This would prevent the following error from happening.

Long

**Comment by Ploypiti** [comment]
@abishekvashok @duttaditya18 Indented & Fixed height.

**Review by realslimshanky — APPROVED** [review]
LGTM

**Review by nzec — APPROVED** [review]
Good Work! 🐍

**Review by ParthS007 — APPROVED** [review]

**Pull request merged**
