### PR TITLE
Changed Copyright year to 2014-2015

### PR DESCRIPTION
**Pull request by Parbhat**

### CODE REVIEW

**Comment by tradzik** [comment]
Hi, thank you for your edits. I think it will be better if you change copyright to "2014-2015", because we worked and site and it was object of our copyrights also in 2014.

**Comment by Parbhat** [comment]
@ty221 Thanks, I am updating the year to 2014-2015

**Comment by Parbhat** [comment]
Copyright year is updated to 2014-2015

**Comment by tradzik** [comment]
Thank you. Pull request merged

**Pull request merged**
