### PR TITLE
Fixes #65 : Added more suitable images for tracks.

### LINKED ISSUE #65: Choose more suitable images for tracks
The tracks in the section "Detailed Schedule and Tracks" have all the same lead image. Please find more suitable images and substitute them.

Ensure:
* the images are not too big in size
* all have the same resolution, height/width for the area
* are in good quality
* come from a FOSSASIA event

### PR DESCRIPTION
**Pull request by nzec**
* Added images of the respective venues.
* Fixes #65 

***Preview Link : https://duttaditya18.github.io/2015.fossasia.org/***

### CODE REVIEW

**Comment by arjunpandey2003** [comment]
LGTM

**Review by arjunpandey2003 — APPROVED** [review]

**Review by saarthakchats — APPROVED** [review]
LGTM!

**Review by amryarios — APPROVED** [review]
LGTM!

**Review by ParthS007 — APPROVED** [review]

**Comment by nzec** [comment]
@ParthS007 Thanks!

**Pull request merged**
