### PR TITLE
Changed Profile Social Links of 8 Speakers which are missing and which are wrong

### PR DESCRIPTION
**Pull request by NaviRocker**
Changes

Andreas Bräu (Germany)  - https://www.linkedin.com/in/andreasbraeu/
Eugene Teo - https://twitter.com/eugeneteo
Jonathan "Duke" Leto - https://www.linkedin.com/in/jaleto/
Jan Jongboom (The Netherlands) - https://www.linkedin.com/in/jan-jongboom/
Bernd Erk - https://twitter.com/gethash
Prashant Kiran (India) - https://twitter.com/prasht63
Vipul Hari - https://www.linkedin.com/in/vipul-hari-884a76127/
Heena Mahour - https://www.linkedin.com/in/heena-mahour-a183ba99/

### CODE REVIEW

**Comment by isuruAb** [comment]
@naveentherocker  please resolve conflicts. there are  193 commits. please check your pull request again. thank you 👍

**Comment by akarshan96** [comment]
@naveentherocker you can close this pull request now.

**Comment by 0x48piraj** [comment]
@naveentherocker I saw another **PR** **#51**. So, You can close this **PR** :wink:

**Comment by NaviRocker** [comment]
Sorry For the Mistake

**Comment by 0x48piraj** [comment]
No Problem Buddy :blush:
You have done a great job! :heart_eyes: 
Keep it up! :+1:

**Pull request closed without merging**
