### PR TITLE
Update index.html (Added missing speaker's list 8+)

### PR DESCRIPTION
**Pull request by yashk0thari**
#70 I've added missing speaker's list (8 links)

### CODE REVIEW

**Comment by yashk0thari** [comment]
https://beta-king.github.io/Beta-King2015.fossasia.org/ --> preview link

**Comment by yashk0thari** [comment]
Please review it ?!?!

**Comment by anshumanv** [comment]
Write properly in PR comment, `Fixes #<issue number>`
Then mention the changes you made, also update PR title to what you did.

**Comment by yashk0thari** [comment]
made necessary changes...

**Comment by anshumanv** [comment]
`Update index.html` is not needed.

Also, try to update your commit message to what it does, since after a month or so nobody will be able to make out what that commit did.

**Comment by yashk0thari** [comment]
I'll have to open another PR to make that change... am doing it right now :D

**Pull request closed without merging**
